spring:
  application:
    name: api-gateway-microservice
  cloud:
    gateway:
      routes:
        - id: sum-service
          uri: lb://sum-microservice
          predicates:
            - Path=/api/sum-service/**
          filters:
            - RewritePath=/api/sum-service(?<segment>/?.*), $\{segment}
        - id: calculator-service
          uri: lb://calculator-microservice
          predicates:
            - Path=/api/calculator/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/eureka-app/**
          filters:
            - RewritePath=/eureka-app(?<segment>/?.*), $\{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace
server:
  port: 9999