spring:
  application:
    name: api-gateway-microservice
  cloud:
    gateway:
      routes:
        - id: sum-service
          uri: lb://sum-microservice
          predicates:
            - Path=/api/sum-service/**
          filters:
            - RewritePath=/api/sum-service(?<segment>/?.*), $\{segment}
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace
server:
  port: 9000