spring:
  application:
    name: calculator-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9999

app:
  sum: 
    host: http://api-gateway-microservice/api/sum-service/